services:
  database:
    image: mysql:latest
    tty: true
    container_name: database
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projeto_imoveis
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 15s
      timeout: 10s
    profiles: ['prod', 'dev']
  api-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    tty: true
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src:/home/app/src
    profiles: ['dev']
volumes:
  mysql_data: 
