services:
  database:
    image: mysql:latest
    tty: true
    container_name: database
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projeto_imoveis
    volumes:
      - mysql_data:/var/lib/mysql
    profiles: ['prod', 'dev']
  api-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - ./src:/home/app/src
    profiles: ['dev']
volumes:
  mysql_data: 
